// Ax.idl : IDL source for Ax
//

// This file will be processed by the MIDL tool to
// produce the type library (Ax.tlb) and marshalling code.

#include "olectl.h"
import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(EEA7C0E0-301E-481A-9208-1878AC7DEB01),
	dual,
	oleautomation,
	nonextensible,
	pointer_default(unique)
]
interface ILeaker : IDispatch{
	[id(1)] HRESULT breakpoint();

	/* disassembler and dumper */
	[propget, id(2)] HRESULT syntax([out, retval] BSTR* pVal);
	[propput, id(2)] HRESULT syntax([in] BSTR newVal);
	[propget, id(3)] HRESULT bits([out, retval] LONG* pVal);
	[propput, id(3)] HRESULT bits([in] LONG newVal);
	[id(4)] HRESULT disassemble([in] ULONGLONG ea, [in] LONG n, [out, retval] BSTR* result);
	[id(5)] HRESULT dump([in] ULONGLONG ea, [in] LONG n, [in] BSTR type, [out, retval] BSTR* result);

	/* integer extraction */
	[id(6)] HRESULT uint8_t([in] ULONGLONG ea, [out, retval] ULONG* result);
	[id(7)] HRESULT sint8_t([in] ULONGLONG ea, [out, retval] LONG* result);
	[id(8)] HRESULT uint16_t([in] ULONGLONG ea, [out, retval] ULONG* result);
	[id(9)] HRESULT sint16_t([in] ULONGLONG ea, [out, retval] LONG* result);
	[id(10)] HRESULT uint32_t([in] ULONGLONG ea, [out, retval] ULONG* result);
	[id(11)] HRESULT sint32_t([in] ULONGLONG ea, [out, retval] LONG* result);
	[id(12)] HRESULT uint64_t([in] ULONGLONG ea, [out, retval] ULONG* result);
	[id(13)] HRESULT sint64_t([in] ULONGLONG ea, [out, retval] LONG* result);
	[id(14)] HRESULT binary32([in] ULONGLONG ea, [out, retval] FLOAT* result);
	[id(15)] HRESULT binary64([in] ULONGLONG ea, [out, retval] DOUBLE* result);

	/* string extraction */
	[id(16)] HRESULT unicodestring([in] ULONGLONG ea, [out, retval] BSTR* result);
	[id(17)] HRESULT ansistring([in] ULONGLONG ea, [out, retval] BSTR* result);

	/* ndk wrappers */
	[id(18)] HRESULT getPeb([out, retval] ULONGLONG* PebBaseAddress);
	[id(19)] HRESULT getTeb([in] ULONG dwThreadId, [out, retval] ULONGLONG* TebBaseAddress);
	[id(20)] HRESULT getlasterror([out, retval] ULONG* dwErrorCode);
	[id(21)] HRESULT geterrormessage([in] ULONG dwErrorCode, [out, retval] BSTR* bstrErrorMessage);

	/* virtualquery wrappers */
	[id(22)] HRESULT mem_baseaddress([in] ULONGLONG ea, [out, retval] ULONGLONG* result);
	[id(23)] HRESULT mem_size([in] ULONGLONG ea, [out, retval] ULONGLONG* result);
	[id(24)] HRESULT mem_state([in] ULONGLONG ea, [out, retval] ULONGLONG* result);
	[id(25)] HRESULT mem_protect([in] ULONGLONG ea, [out, retval] ULONGLONG* result);
	[id(26)] HRESULT mem_type([in] ULONGLONG ea, [out, retval] ULONGLONG* result);
};

[
	uuid(D0480AA4-1478-406F-B73C-6E28F7C31F87),
	version(1.0),
]
library AxLib
{
	importlib("stdole2.tlb");
	[
		uuid(2C4E75A2-7EDC-4886-B7BA-0EABA901899F),		
		control
	]
	coclass Leaker
	{
		[default] interface ILeaker;
	};
};

